# Root directory
rootDirectory: /Users/astronauta/Dropbox/admin zakelijk

# Category
category: 1. Inkoop

# My companies
myCompanies:
- Hooplot Holding BV
- Hooplot Media BV

# Customers
customers:
- 123Inkt
- Amazon
- ANWB
- CJIB
- Coolblue
- Crashplan
- DropBox
- Finovion
- Flexwebhosting
- MediaMarkt
- MKBBrandstof
- NSBusiness
- Parkeergarage
- Parkmobile
- Restaurant
- T-Mobile
- Ziggo