# Root directory
rootDirectory: /Users/astronauta/Dropbox/admin zakelijk

# Root directory
category: 1. Inkoop

# My companies
myCompanies:
	- Hooplot Holding BV
	- Hooplot Media BV

# Customers
customers:
  - Flexwebhosting
  - MediaMarkt
  - NSBusiness
  - Parkmobile
  - MKBBrandstof
  - Amazon
  - Ziggo
  - CJIB
  - 123Inkt
  - ANWB
  - Restaurant
  - Crashplan
  - DropBox
  - Finovion
